# Generated by Django 4.2.2 on 2023-06-17 23:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subject',
            name='porfessor',
            field=models.CharField(default=23, max_length=255),
            preserve_default=False,
        ),
    ]
