# Generated by Django 4.2.2 on 2023-06-18 00:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0002_subject_porfessor'),
    ]

    operations = [
        migrations.RenameField(
            model_name='subject',
            old_name='porfessor',
            new_name='professor',
        ),
    ]
